import Head from 'next/head'
import Image from 'next/image'
import { GetStaticProps } from 'next'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Container, IconButton, ImageList, ImageListItem, ImageListItemBar } from '@mui/material'
import { Info } from '@mui/icons-material'
import Feed from '../components/Feed'
import useSWR, { useSWRConfig, preload, SWRConfig } from 'swr'
import { useState, useEffect } from 'react'
import Header from '../components/Header'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

// const getPostsFromAPI = async () => {
//   const posts = await fetch('http://catstagram.lofty.codes/api/posts/').then((res) => res.json())
//   return posts
// }

// export async function getStaticProps () {
//   const posts = await getPostsFromAPI()
//   return  {
//     props: {
//       fallback: {
//         'http://catstagram.lofty.codes/api/posts/': posts
//       }
//     }
//   }
// }

export default function Home() {

  // const { cache } = useSWRConfig()
  // console.log(cache, '<-- cache from homepage')

  const [posts, setPosts] = useState([])

  useEffect(() => {
    const getPostsFromAPI = async () => {
      const posts = await fetch('http://catstagram.lofty.codes/api/posts/').then((res) => res.json())
      setPosts(posts)
    }
    getPostsFromAPI()
  }, [])

  return (
    <>
      <Head>
        <title>Lofty Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href='http://catstagram.lofty.codes/api/posts/' as="fetch" />
      </Head>
      <Header />
      <Feed posts={posts}/>
      <Footer />
    </>
  )
}
